services:
  - type: web
    name: powersports-backend
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DB_DIRECTORY
        value: '/var/data'
    databases:
      - name: powersports-db

databases:
  - name: powersports-db
    plan: free
    region: oregon
